// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SearchAggregator.Repositories;

namespace SearchAggregator.Migrations
{
    [DbContext(typeof(SearchAggregatorContext))]
    partial class SearchAggregatorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("SearchAggregator.DataAccess.Models.Keyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Word")
                        .IsUnique();

                    b.ToTable("Keyword");
                });

            modelBuilder.Entity("SearchAggregator.DataAccess.Models.KeywordResource", b =>
                {
                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KeywordId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("KeywordResource");
                });

            modelBuilder.Entity("SearchAggregator.DataAccess.Models.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resource");
                });

            modelBuilder.Entity("SearchAggregator.DataAccess.Models.KeywordResource", b =>
                {
                    b.HasOne("SearchAggregator.DataAccess.Models.Keyword", "Keyword")
                        .WithMany("KeywordResources")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SearchAggregator.DataAccess.Models.Resource", "Resource")
                        .WithMany("KeywordResources")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("SearchAggregator.DataAccess.Models.Keyword", b =>
                {
                    b.Navigation("KeywordResources");
                });

            modelBuilder.Entity("SearchAggregator.DataAccess.Models.Resource", b =>
                {
                    b.Navigation("KeywordResources");
                });
#pragma warning restore 612, 618
        }
    }
}
